### ISSUE TITLE
2017년 06월 08일 목요일 17:00 회의

### ISSUE THREAD

**Issue by rudebono** [rudebono/dguchat#1]
날짜 : 2017년 06월 08일 목요일

시간 : 17:00

장소 : 알파실 

내용 :
1부 - 현재 까지 프로젝트 진행 총 정리 (석정한)
2부 - 깃허브 README.md 작성 가이드라인 소개 (석정한)
3부 - Mardown 문법 소개 (천훼)
4부 - 가이드라인에 맞게 작성 (석정한, 강정석, 심희오, 천훼)
5부 - 기타

준비물 : 
1. 노트북
2. 채팅방 사용 방법 문서 (천훼)
3. Qt 소개 문서 (강정석, 심희오)
4. WebRTC 소개 문서 (석정한)

**Comment by ims21c** [comment]
확인 완료. 열심히 준비해서 모여서 좋은 결과물 만듭세요!!

**Comment by kang-jungseok** [comment]
확인
