### ISSUE TITLE
2017년 06월 14일 수요일 발표 대비 공지사항

### ISSUE THREAD

**Issue by rudebono** [rudebono/dguchat#2]
1. https://github.com/rudebono/dguchat/ 의 README.md 수정
- dguchat 이용 방법 (한국어, 중국어)
- 천훼

2. https://github.com/rudebono/dguchat/tree/master/client 에 qt 소스 올리기
- source 폴더 하나 만들어서 안에 qt 소스 올리기
- source 폴더 안에 소스를 업로드 후 README.md 파일 만들기
- source 폴더 안 README.md 파일에 qt 소스코드 분석한거 올리기
- 강정석, 심희오

3. https://github.com/rudebono/dguchat/tree/master/client 에 exe, .out 파일 올리기
- 윈도우즈용, 우분투용 클라이언트 프로그램 올리기
- README.md 파일 만들기
- README.md 파일 안에 해당 프로그램을 사용할 수 있게 qt 라이브러리 설치방법 올리기
- 강정석, 심희오

4. 모든 README.md 중국어로 번역하기
- https://github.com/rudebono/dguchat 의 README.md
- https://github.com/rudebono/dguchat/tree/master/server 의 README.md
- https://github.com/rudebono/dguchat/tree/master/client 의 README.md
- https://github.com/rudebono/dguchat/tree/master/client/source 의 README.md
- https://github.com/rudebono/dguchat/tree/gh-pages 의 README.md
- 천훼

5. 1번~4번 위 해야할 일은 발표일 (수요일) 수업 시간 전까지 해결 바람. 되도록이면 천훼씨 도와서 같이 진행.

6. 최종 보고서 깃허브에 업로드했음. 참고 바람.

7. 최종 PPT 만들기
- 차후 https://github.com/rudebono/dguchat/tree/master/homework 에 최종 보고서 PPT 폴더 생성할 예정임.
- 해당 폴더에 각자 해당 하는 발표 부분을 화요일 오후 11시 59분 까지 업로드 바람.
- 종합하여 새벽 3시 이전에 업로드 하겠음.
- 만약 화요일 오후 11시 59분까지 업로드 안될 시 내가 만든 피피티로 진행하겠음.

시간 엄수 잘해주고 마지막까지 힘내시길...

**Comment by ims21c** [comment]
확인하였습니다!
