### ISSUE TITLE
최종 발표 PPT 올라왔습니다.

### ISSUE THREAD

**Issue by rudebono** [rudebono/dguchat#8]
https://github.com/rudebono/dguchat/tree/master/homework/20170614_%EC%B5%9C%EC%A2%85%EB%B0%9C%ED%91%9C

최종 발표 PPT
석정한 : 1p~12p & 24p~26p
강정석, 심희오 : 13p~21p
천훼 : 22p ~ 23p

ppt 밑에 대본 있습니다.
참고 하세용~

**Comment by kang-jungseok** [comment]
오키요~

**Comment by ims21c** [comment]
확인 잘합쳐졌군!!
